describe('Button', () => {
  test('renders name', () => {})
  test('renders color', () => {})
  test('renders bg color', () => {})
  test('renders border', () => {})
  test('renders border radius', () => {})
  test('renders shadow', () => {})
  test('changes on hover', () => {})
  test('emits event', () => {})
})